# Generated by Django 6.0.3 on 2026-03-20 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10)),
                ('invoice_date', models.DateField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('mode_of_payment', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_po_no', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_po_date', models.DateField(blank=True, null=True)),
                ('eway_bill_no', models.CharField(blank=True, max_length=50, null=True)),
                ('einvoice_no', models.CharField(blank=True, max_length=50, null=True)),
                ('insurance_no', models.CharField(blank=True, max_length=50, null=True)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('shipping_charges', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('round_off', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_in_words', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('hsn_code', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('manufacturer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('date_code', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
            ],
        ),
    ]
