# Generated by Django 6.0.3 on 2026-03-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50, unique=True)),
                ('item_name', models.CharField(max_length=255)),
                ('manufacturer_part_number', models.CharField(max_length=100)),
                ('manufacturer_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('resistor', 'Resistor'), ('capacitor', 'Capacitor'), ('ics', 'ICs'), ('conductors', 'Conductors'), ('diode', 'Diode'), ('connector', 'Connector'), ('mosfets', 'MOSFETs')], max_length=20)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('last_purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_order_quantity', models.PositiveIntegerField()),
                ('sales_unit', models.CharField(choices=[('nos', 'Nos'), ('reel', 'Reel'), ('tray', 'Tray')], max_length=10)),
                ('datasheet_link', models.URLField(blank=True, null=True)),
                ('hsn_code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
