# Generated by Django 6.0.3 on 2026-03-27 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoices.item'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
