# Generated by Django 6.0.3 on 2026-03-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoiceitem_item_alter_invoiceitem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer_po_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer_po_no',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='einvoice_no',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='eway_bill_no',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='gst_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='insurance_no',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='mode_of_payment',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='round_off',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='shipping_charges',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='customer_item_code',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='date_code',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='manufacturer_name',
        ),
        migrations.AddField(
            model_name='invoice',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='igst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='gst_slab',
            field=models.CharField(choices=[('18_9_9', 'IGST 18%, CGST 9%, SGST 9%'), ('18_2.5_2.5', 'IGST 18%, CGST 2.5%, SGST 2.5%'), ('12_6_6', 'IGST 12%, CGST 6%, SGST 6%')], default='18_9_9', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='gst_percentage',
            field=models.PositiveIntegerField(choices=[(18, '18%'), (12, '12%'), (5, '5%')], default=18),
        ),
        migrations.AddField(
            model_name='item',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount_in_words',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='manufacturer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='manufacturer_part_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='minimum_order_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sales_unit',
            field=models.CharField(blank=True, choices=[('nos', 'Nos'), ('reel', 'Reel'), ('tray', 'Tray')], max_length=10, null=True),
        ),
    ]
