# Generated by Django 6.0.3 on 2026-03-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_remove_invoice_customer_po_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='igst',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='sgst',
        ),
        migrations.RemoveField(
            model_name='item',
            name='gst_percentage',
        ),
        migrations.AddField(
            model_name='invoice',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('resistor', 'Resistor'), ('capacitor', 'Capacitor'), ('ics', 'ICs'), ('conductors', 'Conductors'), ('diode', 'Diode'), ('connector', 'Connector'), ('mosfets', 'Mosfets')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='hsn_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='manufacturer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='manufacturer_part_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='minimum_order_quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='sales_unit',
            field=models.CharField(choices=[('nos', 'Nos'), ('reel', 'Reel'), ('tray', 'Tray')], max_length=10),
        ),
    ]
