# Generated by Django 6.0.3 on 2026-04-01 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_customer_buyer_project_name_and_more'),
        ('invoices', '0005_remove_invoice_cgst_remove_invoice_igst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='authorized_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.company'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_po_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_po_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='dispatch_courier_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='dispatch_docket_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='dispatch_mode',
            field=models.CharField(blank=True, choices=[('COURIER', 'Courier'), ('HAND_DELIVERY', 'Hand Delivery'), ('POST', 'Post')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='e_invoice_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='e_way_bill_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='insurance_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='mode_of_payment',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('ONLINE', 'Online Transfer'), ('CREDIT', 'Credit')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='prepared_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='round_off',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms_conditions_duplicate',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms_conditions_extra',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms_conditions_original',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='verified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='customer_item_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='date_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='manufacture_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
