# Generated by Django 6.0.3 on 2026-03-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('customer_id', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('contact_person_name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee (INR)'), ('USD', 'US Dollar (USD)')], max_length=3)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('preferred_courier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_courier_mode', models.CharField(blank=True, choices=[('AIR', 'Air'), ('SURFACE', 'Surface')], max_length=10, null=True)),
                ('industry', models.CharField(blank=True, choices=[('CONSUMER', 'Consumer'), ('INDUSTRIAL', 'Industrial'), ('AUTOMOTIVE', 'Automotive'), ('DEFENCE', 'Defence / Space / Navy'), ('MEDICAL', 'Medical'), ('RAILWAYS', 'Railways & Transportation'), ('LIGHTNING', 'Lightning'), ('EMS', 'EMS'), ('PREMIUM', 'Premium'), ('LOW_COST', 'Low Cost'), ('TRADER', 'Trader')], max_length=20, null=True)),
                ('customer_products', models.TextField(blank=True, null=True)),
                ('sales_person', models.CharField(blank=True, max_length=200, null=True)),
                ('territory', models.CharField(blank=True, choices=[('WEST', 'West'), ('EAST', 'East'), ('NORTH', 'North'), ('SOUTH', 'South')], max_length=10, null=True)),
                ('dispatch_address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_enrollment', models.DateField(blank=True, null=True)),
                ('lead_source', models.CharField(blank=True, choices=[('EXHIBITION', 'Exhibition'), ('EMAIL', 'Email'), ('WEBSITE', 'Website'), ('CALL', 'Call'), ('LINKEDIN', 'LinkedIn'), ('OLD_CUSTOMER', 'Old Customer'), ('MARKET', 'Market')], max_length=20, null=True)),
                ('annual_purchase_potential', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('last_financial_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('customer_turnover', models.CharField(blank=True, choices=[('VERBAL', 'Verbal'), ('ONLINE', 'Online (MCA)')], max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
