# Generated by Django 6.0.3 on 2026-04-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('address', models.TextField()),
                ('gst_no', models.CharField(max_length=20)),
                ('state_name', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=10)),
                ('cin_no', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=15)),
                ('pan_no', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_account_no', models.CharField(max_length=50)),
                ('bank_ifsc', models.CharField(max_length=20)),
                ('bank_branch', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='buyer_project_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_review_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='creditability_rating',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='lc_terms',
            field=models.CharField(blank=True, choices=[('30', '30 Days'), ('45', '45 Days'), ('60', '60 Days'), ('90', '90 Days')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='oc_terms',
            field=models.CharField(blank=True, choices=[('30', '30 Days'), ('45', '45 Days'), ('60', '60 Days'), ('90', '90 Days')], null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pan_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('ADVANCE', 'Advance'), ('ADVANCE_PDC', 'Advance PDC'), ('30_DAYS', '30 Days'), ('45_DAYS', '45 Days'), ('60_DAYS', '60 Days'), ('90_DAYS', '90 Days')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='state_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
