# Generated by Django 6.0.3 on 2026-03-28 10:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('invoices', '0005_remove_invoice_cgst_remove_invoice_igst_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('quotation_date', models.DateField(default=django.utils.timezone.now)),
                ('contact_person', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('inquiry_source', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp / Messenger'), ('PHONE', 'Phone'), ('EXHIBITION', 'Exhibition'), ('WEBSITE', 'Website'), ('REFERENCE', 'Reference')], max_length=20)),
                ('sales_person', models.CharField(max_length=255)),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], default='INR', max_length=10)),
                ('freight_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('validity_days', models.PositiveIntegerField(default=7)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CONVERTED', 'Converted to Invoice')], default='DRAFT', max_length=20)),
                ('lead_time', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_docket_details', models.TextField(blank=True, null=True)),
                ('dispatch_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('mpn', models.CharField(blank=True, max_length=255)),
                ('date_code', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst_percentage', models.PositiveIntegerField(default=18)),
                ('packaging_type', models.CharField(choices=[('REEL', 'Reel'), ('TRAY', 'Tray'), ('TUBE', 'Tube'), ('LOOSE', 'Loose')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_with_gst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoices.item')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotation')),
            ],
        ),
    ]
